### ISSUE TITLE
Depth loading leads to a lot of additional requests

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/js-sdk#10]
Hey there,

it is me again *narf :).

I played around a little bit deeper and i do not get it why the "depth" option leads to such a mass of additional requests.

e.g. I have blog Posts -> connected to a Set of Comments and Tags.

When i do the following:
```
db.Post.find().resultList({depth: 1})
```

There is a request for each comment. What is quite heavy and costs time, bandwidth and requests ;).

I would expect (from a mongodb/mongoose background) that there is one request `populate`ing the comments and retrieve them as a list.

**Comment by malte-lau** [comment]
Hi Bengt,
a good question.
Of cause, we have considered various behaviours and went through extensive testing.

With caching and HTTP/2 (h/2) we have seen an increasing advantage of getting the objects individually. With h/2 the additional bandwidth is negligible and in almost all scenarios we could see a reduction in page load time due to increased cache-hit rates.

Especially in the common scenario where shared private Objects are depth loaded, the CDN cache-hit rate drop when bundling Objects. We were working on various ways of merging bundle ACLs, but using "h/2-push" and validate object-ACL individually is now simply the better and faster option.

Secondly, bundling results lead to higher Invalidation rates because of each update on any object would trigger the invalidation and reduce the optimal lifetime of this and all similar bundles.

But of course, it takes more request. In your case, especially since you are not yet using ssl and h/2, we should find a better solution.

Do Tags and Comments share the same ACLs as Posts? In that case, you could use embedded Objects, that might lead to the behaviour you had expected from your MongoDB experience.

If they have separate access rights, you could instead of using depth, query Comments and Tags separately after a Post is opened.

If you want to print all Posts and all Comments on one side, like Facebook dose it is reasonable to add lazy loading similar to their approach.

Best Regards
Malte

**Comment by KillerCodeMonkey** [comment]
yeah, for sure... i understand the things you described. 
Comments are individual per post. so i could drop the additional comments scheme for embedding objects.

But tags are shared so i can easily implement something like "get posts by tag".

Do i have access to the ids of tags and comments without deep loading?
so Post -> has a field "tags" as a Set<Tag>. So i can request all tags by one additional get:

```
db.Tag.find().in('id', post.tags).resultList()
```
?

**Comment by malte-lau** [comment]
Yes, sure.

Just the Set type is introducing a problem here.
We should make this more clear in the guide.
The collection operators expect a List or Array type.

For example you can do:
```js
 db.Tag.find().in('id', Array.from(post.tags)).resultList()
```

**Comment by KillerCodeMonkey** [comment]
Yeah, you are totally right. I forget sometimes that there are the "new" types in javascript and we have to use `.size` and not `.length` and so on :)

i close this issue. Thanks!
