### ISSUE TITLE
Websocket missing as peer dependency 'npm install -save baqend'

### ISSUE THREAD

**Issue by Booli** [Baqend/js-sdk#4]
Hey,

as per title. Running 

`npm install -save baqend`

throws a missing peer dependency for websocket@1.0.22 
`-- UNMET PEER DEPENDENCY websocket@^1.0.22` 
`npm WARN baqend@2.3.1 requires a peer of websocket@^1.0.22 but none was installed.`

Running on Windows 10. 
`λ node -v
v6.5.0`

`λ npm -v
3.10.3`

**Comment by fbuecklers** [comment]
Hi, 
that is not an error, since it is currently not possible to define an optional peer dependency with npm. The websocket npm module is only required when you want to use our new real-time API with node.js (still beta). 

If you want to prevent the warning or want to use the real-time API install the websocket module and add it to your project dependencies:

``` sh
npm install --save websocket
```

Note that you need [node-gyp](https://github.com/nodejs/node-gyp) installed to install the websocket module. 

You can also ignore the WARN message, the SDK will work for you without that peer module.
