### ISSUE TITLE
How to mock js-sdk for unit testing

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/js-sdk#7]
Heyho,

i am playing around with baqend + angular 2 and i am at a point, where i want to test a service, that is using baqend.

So how can i easily mock/stub the db object?

**Comment by fbuecklers** [comment]
Hi,

currently, there is no easy solution to mock the entire db. What do you expect how a db mock should behave? Since the SDK just wraps the API calls which access the Data from Baqend.

Regards Florian

**Comment by KillerCodeMonkey** [comment]
ehhm, sure i could simply use angular 2 mockbackend to simply avoid the app sending real requests during tests, but to use the db it has to be connected. So this is no way.

I can not set any spy with jasmine, because calls are chained like

```
db.myModel.find()
    .limit(30)
    .resultList()
    .then(() => { // this part needs to be tested })
```

What i could do: creating additional named functions for my callbacks, to simply test this logic... but it is not the good way to change the code, to make it testable.

**Comment by fbuecklers** [comment]
Yes sure, but it is not so easy to provide a generic mock since the `db.myModel` properties a generated dynamically depending on your schema. Therefore a Baqend schema is required to provide a mock for your app and that schema is fetched when the SDK connects to Baqend. 

But it is possible to mock chained calls also with jasmine:
http://stackoverflow.com/questions/27971729/how-to-unit-test-a-chained-method-using-jasmine#answer-27972057

It may be possible to provide a mocked Baqend connector wich just provide some dummy data. But that is not so easy, that is why we currently do not provide any db mocks. But if you have some ideas how to implement that you are always welcome.

**Comment by KillerCodeMonkey** [comment]
Hey, thanks for the ultra fast response. 👍 

Maybe it would be enough to have something like a dbmock --> where connection is set to isReady and as a developer i can set something like a datastore. like dbMock.setData({ Post: [{}] ) and so on. 

Instead of building real queries it could return simply the whole datastore for resultList or one for the singleResult.

But i agree that this is not that easy.

Sadly, my test will be 90% stubbing and 10% testing ^^.

Greetings from germany.

PS: you can really close this issue, if you have no plan or idea to add a testsuite/mock.

**Comment by KillerCodeMonkey** [comment]
ended up doing simple stubbing. ugly but it is working :D

```
import { db } from 'baqend';

// ...

db.Post = {} as any; // model i want to mock
db.Post.find = {
    descending: (field: string) => {
        return {
            limit: (count: number) => {
                return {
                    resultList: () => Promise.resolve(data)
                };
            }
        }
    },
    equal: (field: string, value: any) => {
        return {
            singleResult: () => Promise.resolve(data[0])
        };
    }
}
```
